services:
  airconnect:
    build: .
    image: airconnect:local
    container_name: airconnect
    network_mode: host
    restart: unless-stopped
    # Environment variables to configure the bridges
    environment:
      - AIRUPNP_VAR=-l 1000:2000
      # - AIRCAST_VAR=-x /config/aircast.xml
      # To disable one of the services, set its variable to 'kill'
      # - AIRUPNP_VAR=kill
      # - AIRCAST_VAR=kill
    # Optional: mount a config directory
    # volumes:
    #   - ./config:/config
